### ISSUE TITLE
Setting operation name

### ISSUE THREAD

**Issue by carlosalberto** [opentracing-contrib/java-okhttp#12]
The current operation name for each Span is the request method, i.e. `POST`, `GET`, `PUT`, etc, which is probably too generic. So, was thinking: would it be ok to provide, instead, the `url` request? Like `api/2.0/get_cookies`?

Either that, or let the user provide a function/class that lets specify the operation name out of a request, i.e.

`String getOperationName (request) { ... }`

Would that be fine? Based on what you tell me, I can start working on a small PR ;)

EDIT: Oh, the same happens for other components, like the the `web-servlet` one ;)

**Comment by objectiser** [comment]
As you say, it is a problem faced by all of the framework integrations. Have started a general discussion here: https://github.com/opentracing-contrib/meta/issues/25

Might be good to see if we can come up with a consistent approach.

**Comment by pavolloffay** [comment]
Operation name can be set in decorators, closing for now.
