### ISSUE TITLE
Question around Usage

### ISSUE THREAD

**Issue by ashutoshraina** [opentracing-contrib/java-okhttp#16]
Hello,

My goal is to pass in additional meta-data using the inject-extract combo. However, I am unable to get the inject bits to work correctly. I am currently using the RequestBuilderInjectAdapter as follows. 

```
       Request.Builder builder = new Request.Builder().url(url);
        RequestBuilderInjectAdapter injectAdapter = new RequestBuilderInjectAdapter(builder);
        injectAdapter.put("X-B3-Foo", "Bar");

        Response response = client.newCall(builder.build()).execute();
```

On the receiver side I am able to do the following 

```
         Map<String, String> httpHeaders = getHeaders(request);
        TextMapExtractAdapter carrier = new TextMapExtractAdapter(httpHeaders);
        SpanContext parentSpan = tracer.extract(HTTP_HEADERS, carrier);

     ... do some more work with the span
```

Notice, that there is no inject on the tracer instead we are using the adapter which quite simply adds the additional metadata to the httpheaders in the underlying builder. Using inject doesn't automatically bind the additional headers to the outgoing request.

How can I use the inject/extract combination with instrumented OKHttp ?

**Comment by pavolloffay** [comment]
Hi @ashutoshraina,

passing additional headers should work. Here is an example https://github.com/pavolloffay/java-okhttp/commit/d308ff89113388ffaf58ed2005d7318991e8242d.

You don't have to use ` RequestBuilderInjectAdapter`, you can directly pass any additional headers via request builder.

**Comment by ashutoshraina** [comment]
Thanks for the example. My question was more around how tracer.inject would play with this i.e. can I achieve the same thing via `tracer.inject` (if so how) or `RequestBuilderInjectAdapter` the only way to go.

**Comment by pavolloffay** [comment]
This library automatically injects all necessary headers to an outbound request. By necessary I mean a specific tracer implementation decides which headers are injected (this differs for zipkin/jaeger/lightstep). 

If you want to propagate other headers it's up to you. You might want to look at OpenTracing feature called baggage http://opentracing.io/documentation/pages/instrumentation/common-use-cases.html#using-baggage--distributed-context-propagation.
