### ISSUE TITLE
Propagation Help 

### ISSUE THREAD

**Issue by aaronkorver** [opentracing-contrib/java-okhttp#21]
With this library I can start spans just fine.  I'm attempting to add this to an existing project and I can't seem to find the magic sauce to get things to join existing propagations.   I can see where things get injected, but if I'm calling a service and something already exists, should it be extracting it somehow from a carrier?

Use Case here is start trace --> do processing --> call external API --> finish process --> finish trace

With the library I will get two different spans, but the external API won't be set as a child of the process span.  Help is appreciated as I'm thinking I'm doing it wrong 😄

**Comment by yurishkuro** [comment]
this lib should be linking to the current active span in the ScopeManager. If there is no such span it will start a new trace. You may be missing the span because either (a) your server framework doesn't store it there, or (b) because you are using extra threads during the processing and the context is getting lost (in which case you can wrap the thread pool / executors using https://github.com/opentracing-contrib/java-concurrent).

**Comment by aaronkorver** [comment]
@yurishkuro thanks for the response.  When you start a span with the SpanBuilder, is it automagically added to the ScopeManager then?  Or is there a manual registration necessary?

**Comment by yurishkuro** [comment]
you need to call `startActive()` on the builder to make the span current in the ScopeManager.

**Comment by aaronkorver** [comment]
Dug into the Jaeger code and realized that ScopeManger is a ThreadLocal and tied per Tracer.  I am abusing Tracer I think in that I have more than one per application (jvm).

**Comment by pavolloffay** [comment]
@aaronkorver did you manage to solve this issue?

**Comment by aaronkorver** [comment]
@pavolloffay not yet, spent yesterday refactoring with the new insights from @yurishkuro 

I can close the issue though, unless you want to keep it open for updates?

**Comment by pavolloffay** [comment]
It can be closed, there span propagation works via span manager

**Comment by aaronkorver** [comment]
The reason I'm opening is to report back.  I have gotten it working, but wanted to verify that this an ok pattern.  We were closing the span and the scope at the end of the service.  So the okhttp call was starting a new span but there wasn't an existing active scope to add itself to.  In this case, I don't know where to close the scope.

Second question that arises now, is that the components are actually more of a follows, not a childOf.  Is there a way to support that in this lib?

**Comment by yurishkuro** [comment]
If the code that uses okhttp is meant to run async from the main server span (i.e. a fire & forget use case),  then you can create a Follows-From span while the server span is still active and use that as the active span from which okhttp will create a normal child-of span.

**Comment by pavolloffay** [comment]
@aaronkorver If there is no active span/scope okttp client will create a span and finish it after HTTP call is done so you don't have to manage it explicitly. 

> Second question that arises now, is that the components are actually more of a follows, not a childOf. Is there a way to support that in this lib?

In this case, the parent span would have to be passed explicitly via a tag (okhttp tag).

**Comment by pavolloffay** [comment]
Some client instrumentations support passing span explicitly. in this case passed span takes precedence over active span. This would be your case, but you would have to also specify the relationship.

**Comment by aaronkorver** [comment]
Hmm...alright, thanks for the tips @yurishkuro and @pavolloffay
