### ISSUE TITLE
Should not depend on opentracing-concurrent

### ISSUE THREAD

**Issue by safris** [opentracing-contrib/java-okhttp#29]
Currently, opentracing-http3 depends on opentracing-concurrent. This effectively makes opentracing-http3 an instrumentation plugin that instruments both OkHttp3 and Java's Concurrent package. If one wanted to instrument only OkHttp, he would not be able to do so.

Specifically, it is [this line](https://github.com/opentracing-contrib/java-okhttp/blob/4ad6dbac1b8d70c250dfe3f5684d3ae62449eea7/opentracing-okhttp3/src/main/java/io/opentracing/contrib/okhttp3/TracingInterceptor.java#L70) that should be reduced to:

```java
builder.dispatcher(new Dispatcher(Executors.newFixedThreadPool(10)));
```

Nonetheless, I can see the benefit of instrumenting the `ExecutorService` on this line, so an alternate approach would be to expose an API to the user that would offer him a choice whether to instrument the `ExecutorService` or not. Such an API could resemble:

```java
public static OkHttpClient addTracing(OkHttpClient.Builder builder,
                                      Tracer tracer, List<OkHttpClientSpanDecorator> decorators, ExecutorService executorService) {
    TracingInterceptor tracingInterceptor = new TracingInterceptor(tracer, decorators);
    builder.interceptors().add(0, tracingInterceptor);
    builder.networkInterceptors().add(0, tracingInterceptor);
    builder.dispatcher(new Dispatcher(executorService));
    return builder.build();
    }
```

This way, the user has a choice whether he'd like to provide a bare or instrumented `ExecutorService`.

With this API change, the dependency on Java's Concurrent instrumentation plugin can be removed, specifically this one:

```xml
<dependency>
  <groupId>io.opentracing.contrib</groupId>
  <artifactId>opentracing-concurrent</artifactId>
  <version>${version.io.opentracing-concurrent}</version>
</dependency>
```

**Comment by pavolloffay** [comment]
We can provide an additional API where exec. service can be supplied, however the default behaviour should instrument the exec service if it is necessary for instrumentation to propagate the spans downstream.

**Comment by safris** [comment]
I'm also realizing that the constructor for `TracingInterceptor` can be used directly, which would allow one to avoid the `addTracing()` method that instantiates a `TracedExecutorService`. The SpecialAgent can then safely exclude opentracing-concurrent from the dependency graph of opentracing-http3.
