### ISSUE TITLE
confuse About span name

### ISSUE THREAD

**Issue by wuyupengwoaini** [opentracing-contrib/java-okhttp#32]
https://github.com/opentracing-contrib/java-okhttp/blob/4061cef4fd9d20a454f32fcc18928aa9eb012332/opentracing-okhttp3/src/main/java/io/opentracing/contrib/okhttp3/TracingInterceptor.java#L80-L84

I view the source and I find the default span name is HTTP METHOD(like GET PUT),But I suppose that http uri is a better span name.So I'm confused that why almost every http tracing component uses the HTTP METHOD as as span name.Is there any special consideration?

**Comment by pavolloffay** [comment]
Using URL  would result in high cardinality operation names.

See similar issues https://github.com/opentracing-contrib/java-web-servlet-filter/issues/57
