### ISSUE TITLE
Question about spans

### ISSUE THREAD

**Issue by mattbroekhuis** [opentracing-contrib/java-okhttp#33]
I am noticing that in the UI i use (Jaeger) there are two spans created for each request. You can clearly see this in TracingCallFactory.

Is this to delineate between the setup portion and the actual network operations? Or maybe i have something configured wrong?

**Comment by pavolloffay** [comment]
IIRC each network attempt creates a span and then there is one parent span for the overall client invocation.

One client invocation can have multiple children - for instance when redirects happen.

Please ask questions on the OpenTracing gitter.
